// Google Ads rule pack — transcribed from research/policy_google.md.
// Severity reflects enforcement: high = suspension-risk; med = disapproval/warning; low = advisory.
import type { RulePack } from "@/lib/policy/types";

export const GOOGLE: RulePack = {
  network: "google",
  displayName: "Google Ads",
  rules: [
    // A. Misrepresentation — claims & results
    {
      id: "A1",
      name: "Unrealistic / unreliable results",
      triggers: ["guaranteed", "guaranteed results", "100% effective", "lose 30 lbs in a week", "make $", "results in 24 hours"],
      example: "Guaranteed to make $5,000/week from home!",
      severity: "high",
    },
    {
      id: "A2",
      name: "Get-rich-quick / risk-free financial gain",
      triggers: ["get rich quick", "free money", "risk-free", "double your money", "passive income overnight", "no effort", "guaranteed returns"],
      example: "Turn $100 into $10,000 — risk-free, overnight!",
      severity: "high",
    },
    {
      id: "A3",
      name: "Unrealistic price / availability claims",
      triggers: ["for $1 only", "for $1 —", "claim yours now", "bait pricing"],
      example: "MacBook for $1 — claim yours now!",
      severity: "med",
    },
    {
      id: "A4",
      name: "Unavailable offers",
      triggers: ["offer not on page", "product not available"],
      example: "Ad promotes a product not present on the destination.",
      severity: "high",
    },
    {
      id: "A5",
      name: "False scarcity / urgency / countdowns",
      triggers: ["only 2 left", "offer ends in", "countdown", "timer resets"],
      example: "Hurry! Countdown timer resets every visit.",
      severity: "med",
    },
    {
      id: "A6",
      name: "Fake testimonials / endorsements",
      triggers: ["as seen on", "recommends this", "swears by this", "elon musk recommends"],
      example: "Elon Musk recommends this crypto bot.",
      severity: "high",
    },
    {
      id: "A7",
      name: "False affiliation / impersonation",
      triggers: ["official irs", "government portal", "log in here", "refund portal"],
      example: "Official IRS refund portal — log in here.",
      severity: "high",
    },
    // B. Clickbait & sensationalism
    {
      id: "B1",
      name: "Clickbait phrasing",
      triggers: ["you won't believe", "click here to find out", "doctors hate this", "one weird trick", "the secret they don't want you to know"],
      example: "You won't believe what happened next — click to see!",
      severity: "med",
    },
    {
      id: "B2",
      name: "Negative-emotion pressure",
      triggers: ["lose your home", "about to lose", "before it's too late", "act now or"],
      example: "Are you about to lose your home? Act now!",
      severity: "med",
    },
    {
      id: "B3",
      name: "Sensational imagery",
      triggers: ["before/after", "fungus", "mugshot", "close-up of"],
      example: "Close-up \"fungus\" image to sell supplement.",
      severity: "med",
    },
    {
      id: "B4",
      name: "Misleading ad design",
      triggers: ["virus alert", "system notification", "your computer is infected", "fake close button"],
      example: "Ad styled as a Windows virus alert.",
      severity: "high",
    },
    // C. Affiliate landing pages
    {
      id: "C1",
      name: "Bridge / doorway page",
      triggers: ["go to offer", "click here to continue to offer", "continue to offer"],
      example: "One-page site that just says \"Go to offer →\".",
      severity: "high",
    },
    {
      id: "C2",
      name: "Insufficient original content",
      triggers: ["copy-pasted product description", "scraped content"],
      example: "Copy-pasted product description + affiliate link only.",
      severity: "med",
    },
    {
      id: "C3",
      name: "Destination mismatch",
      triggers: ["display url mismatch", "redirect to different domain"],
      example: "Display bestreviews.com, lands on random-merchant.ru.",
      severity: "med",
    },
    {
      id: "C4",
      name: "Content designed only to show ads",
      triggers: ["ad arbitrage", "made for ads", "frameset"],
      example: "MFA page stuffed with display ads.",
      severity: "med",
    },
    {
      id: "C5",
      name: "Non-functional / dead destination",
      triggers: ["domain for sale", "site not providing services", "parked domain"],
      example: "Landing page returns \"domain for sale\".",
      severity: "med",
    },
    {
      id: "C6",
      name: "Unclear relevance",
      triggers: ["destination unrelated", "ad about x page about y"],
      example: "Ad: \"cheap flights\"; page: weight-loss pills.",
      severity: "med",
    },
    // D. Healthcare & medicines
    {
      id: "D1",
      name: "Prescription drugs without prescription",
      triggers: ["no prescription required", "no rx needed", "no prescription needed", "buy ozempic"],
      example: "Order Ozempic — no prescription required.",
      severity: "high",
    },
    {
      id: "D2",
      name: "Restricted drug terms",
      triggers: ["ozempic", "semaglutide", "wegovy", "viagra"],
      example: "Branded Rx name as headline.",
      severity: "med",
    },
    {
      id: "D3",
      name: "Unapproved / dangerous substances",
      triggers: ["hcg drops", "anabolic steroids", "sarms", "miracle cure"],
      example: "hCG drops for rapid weight loss.",
      severity: "high",
    },
    {
      id: "D4",
      name: "Restricted categories needing certification",
      triggers: ["online pharmacy", "telemedicine", "rehab center", "addiction recovery"],
      example: "Rehab center ad without addiction-services cert.",
      severity: "med",
    },
    {
      id: "D5",
      name: "Misleading health / weight-loss claims",
      triggers: ["cure", "cures", "cures diabetes", "treats diabetes", "clinically proven", "fear-based"],
      example: "Cures diabetes in 30 days — guaranteed.",
      severity: "high",
    },
    // E. Financial services & crypto
    {
      id: "E1",
      name: "Restricted crypto without certification",
      triggers: ["buy bitcoin", "crypto exchange", "trade crypto", "ico", "token sale"],
      example: "Trade Bitcoin on our exchange — sign up.",
      severity: "med",
    },
    {
      id: "E2",
      name: "Prohibited crypto categories",
      triggers: ["crypto signals", "guaranteed 10x picks", "investment advice", "100x picks"],
      example: "Daily crypto signals — guaranteed 10x picks.",
      severity: "high",
    },
    {
      id: "E3",
      name: "Geo-restriction breach",
      triggers: ["unapproved market", "geo-restricted product"],
      example: "Crypto ad served in unapproved market.",
      severity: "med",
    },
    {
      id: "E4",
      name: "Missing financial disclosures",
      triggers: ["no apr shown", "no fees shown", "loan with no apr"],
      example: "Loan ad with no APR or fees shown.",
      severity: "med",
    },
    {
      id: "E5",
      name: "Complex speculative products",
      triggers: ["binary options", "cfd", "rolling spot forex", "spread betting"],
      example: "Trade binary options — fast profits.",
      severity: "med",
    },
    {
      id: "E6",
      name: "Risk misrepresentation",
      triggers: ["zero risk", "risk-free returns", "200% annual return", "guaranteed returns"],
      example: "Stock-trading bot — zero risk, 200% annual return.",
      severity: "high",
    },
    // F. Required disclosures
    {
      id: "F1",
      name: "Disclosure visibility",
      triggers: ["disclosure behind link", "rollover disclosure", "hidden disclosure"],
      example: "Financial disclosure hidden behind a roll-over.",
      severity: "med",
    },
    {
      id: "F2",
      name: "Business identity / contact",
      triggers: ["no contact info", "no physical address", "no license number"],
      example: "Regulated vertical missing physical address / license.",
      severity: "med",
    },
    {
      id: "F3",
      name: "Local-law disclosures",
      triggers: ["jurisdiction disclosure missing"],
      example: "Jurisdiction-specific required statement absent.",
      severity: "low",
    },
  ],
  sourceUrls: [
    "https://support.google.com/adspolicy/answer/6020955",
    "https://support.google.com/adspolicy/answer/15936857",
    "https://support.google.com/adspolicy/answer/6086777",
    "https://support.google.com/adspolicy/answer/15938071",
    "https://support.google.com/adspolicy/answer/15936667",
    "https://support.google.com/adspolicy/answer/6368661",
    "https://support.google.com/adspolicy/answer/16427718",
    "https://support.google.com/adspolicy/answer/176031",
    "https://support.google.com/adspolicy/answer/2464998",
    "https://support.google.com/adspolicy/answer/14009787",
    "https://support.google.com/adspolicy/answer/6008942",
  ],
};
